name: Backend CI

on:
push:
branches:
- main

pull_request:
branches:
- main

permissions:
contents: read

jobs:
backend-build-and-test:
runs-on: ubuntu-latest

steps:
  - name: Checkout repository
    uses: actions/checkout@v7

  - name: Setup .NET 10
    uses: actions/setup-dotnet@v6
    with:
      dotnet-version: '10.0.x'

  - name: Restore dependencies
    run: dotnet restore backend/MiniEmployeePortal.Tests/MiniEmployeePortal.Tests.csproj

  - name: Build backend
    run: dotnet build backend/MiniEmployeePortal.Tests/MiniEmployeePortal.Tests.csproj --no-restore --configuration Release

  - name: Run unit tests
    run: dotnet test backend/MiniEmployeePortal.Tests/MiniEmployeePortal.Tests.csproj --no-build --configuration Release --logger "console;verbosity=normal"